### ISSUE TITLE
Web3极客日报推荐

### ISSUE THREAD

**Issue by yiwen4** [rebase-network/web3daily#6]
标题：一个免费的web3资源库

URL：https://github.com/FrancescoXX/free-Web3-resources

描述：内容很丰富的web3资源库，涉及web3学习路径、区块链基础知识、各开发工具、可参与的开源项目等。

**Comment by xrdavies** [comment]
> 标题：一个免费的web3资源库
> 
> URL：https://github.com/FrancescoXX/free-Web3-resources
> 
> 描述：内容很丰富的web3资源库，涉及web3学习路径、区块链基础知识、各开发工具、可参与的开源项目等。

@liushooter @luckyyang  这个可以推荐到日报里

**Comment by liushooter** [comment]
done 
已推荐到 [Web3 极客日报 #1189](https://mp.weixin.qq.com/s/su-kilrYgt6XesEQS2-4oA)
